//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.24 at 12:15:17 PM MESZ 
//


package org.w3c.wai.accessdb.om.testunit;

import javax.persistence.Entity;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;

import org.w3c.wai.accessdb.om.base.BaseEntity;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement
@Entity
public class RefFileType extends BaseEntity{

    @XmlAttribute(name = "mediatype")
    private String mediatype;
    @XmlAttribute(name = "src")
    private String src;
	

    /**
     * Gets the value of the mediatype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMediatype() {
        if (mediatype == null) {
            return "text/html";
        } else {
            return mediatype;
        }
    }

    /**
     * Sets the value of the mediatype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMediatype(String value) {
        this.mediatype = value;
    }

    /**
     * Gets the value of the src property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrc() {
        return src;
    }

    /**
     * Sets the value of the src property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrc(String value) {
        this.src = value;
    }

}
