//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.24 at 12:15:17 PM MESZ 
//


package org.w3c.wai.accessdb.helpers;

import javax.xml.bind.annotation.XmlRegistry;

import org.w3c.wai.accessdb.om.testunit.RefFileType;
import org.w3c.wai.accessdb.om.testunit.Subject;
import org.w3c.wai.accessdb.om.testunit.TestProcedure;
import org.w3c.wai.accessdb.om.testunit.TestUnitDescription;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.w3.wai.act.asd package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class TestUnitFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.w3.wai.act.asd
     * 
     */
    public TestUnitFactory() {
    }

    /**
     * Create an instance of {@link TestUnitDescription.Procedure }
     * 
     */
    public TestProcedure createTestUnitDescriptionProcedure() {
        return new TestProcedure();
    }

    /**
     * Create an instance of {@link RefFileType }
     * 
     */
    public RefFileType createRefFileType() {
        return new RefFileType();
    }

    /**
     * Create an instance of {@link TestUnitDescription }
     * 
     */
    public TestUnitDescription createTestUnitDescription() {
        return new TestUnitDescription();
    }

    /**
     * Create an instance of {@link TestUnitDescription.Subject }
     * 
     */
    public Subject createTestUnitDescriptionSubject() {
        return new Subject();
    }

}
